-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaKg4OUR6lIZtVIck
IbJjtpzrWJBWVJzJzwb9w4ffqb2gCgYIKoZIzj0DAQehRANCAAQqIhnyCQk1gxE5
H8P4MJ56dX8vlzhKM3wIWJjfrHeN9tAfCdAly22XI1MfSlWXKNhZ1clbjUykmF3t
QOtKbkg0
-----END PRIVATE KEY-----