module.exports = ({
  BookSchema,
  CitySchema,
  CategorySchema,
  CountrySchema,
  StaffSchema,
  ClientSchema,
  ServiceSchema,
  RestaurantSchema,
  MenuSchema,
  RCounterSchema,
  CounterSchema,
  ContactSchema,
  TicketSchema,
  UCounterSchema,
  UserAddressSchema,
  FoodSchema,
  ReviewSchema,
  UserSchema,
  FeeSchema
}, mongoose) => ({
    Book: mongoose.model('Book', BookSchema),
    City: mongoose.model('City', CitySchema),
    Category: mongoose.model('Category', CategorySchema),
    Country: mongoose.model('Country', CountrySchema),
    Staff: mongoose.model('Staff', StaffSchema),
    Client: mongoose.model('Client', ClientSchema),
    Admin: mongoose.model('Admin', StaffSchema),
    Service: mongoose.model('Service', ServiceSchema),
    Restaurant: mongoose.model('Restaurant', RestaurantSchema),
    Menu: mongoose.model('Menu', MenuSchema),
    Rcounter: mongoose.model('Rcounter', RCounterSchema),
    Counter: mongoose.model('Counter', CounterSchema),
    Contact: mongoose.model('Contact', ContactSchema),
    Ticket: mongoose.model('Ticket', TicketSchema),
    Ucounter: mongoose.model('Ucounter', UCounterSchema),
    UserAddress: mongoose.model('UserAddress', UserAddressSchema),
    Food: mongoose.model('Food', FoodSchema),  
    Review: mongoose.model('Review', ReviewSchema),
    User: mongoose.model('User', UserSchema),
    Fees: mongoose.model('Fees', FeeSchema),
})